### ISSUE TITLE
Coin balance shows as 2 on giveaway page

### ISSUE THREAD

**Issue by OranShuster** [RedSparr0w/IndieGala-Helper#10]
after the update to v2 the balance in the giveaway page shows as 2 instead of the number i see in my profile
after manually entering a giveaway the coin balance will update but the extension won't enter any giveaways automatically. also, refreshing the page will show the balance as 2 again

**Comment by RedSparr0w** [comment]
Fixed coin amount shown in latest update.

Currently to get the auto entering giveaways working if you just scroll to the next page it should start entering them automatically, will work on a fix though.
