### ISSUE TITLE
[Request] Custom Description

### ISSUE THREAD

**Issue by GregoryGHarding** [RedSparr0w/IndieGala-Helper#11]
please make available the option in settings to write your own custom description in giveaways instead of static "GLHF"

**Comment by RedSparr0w** [comment]
Updated, added new option 😄

**Comment by GregoryGHarding** [comment]
Most efficient developer I've seen on gh. Lol ty

**Comment by RedSparr0w** [comment]
Thanks [=

Although i just happened to have a bit of spare time to work on this,
Would usually take longer XD.
