### ISSUE TITLE
Suggestion of improvement: don't auto-enter giveaways above your current level.

### ISSUE THREAD

**Issue by omicron321** [RedSparr0w/IndieGala-Helper#12]
In title.

**Comment by RedSparr0w** [comment]
Good idea, will try get this implemented soon.

Will help to reduce load on indiegala servers too.

**Comment by RedSparr0w** [comment]
Closed with [v3](https://github.com/RedSparr0w/IndieGala-Helper/tree/v3) releasing soon.
