### ISSUE TITLE
you can enable auto enter

### ISSUE THREAD

**Issue by GregoryGHarding** [RedSparr0w/IndieGala-Helper#14]
they removed captcha to brainstorm for better solutions. so it can be turned back on in helper now

**Comment by RedSparr0w** [comment]
going to leave it off for now,
still need to work out a max speed and working on a few other features at the moment too.

Edit: fastest speed i seem to have gotten is 1 per 5 seconds without encountering incapsula errors

**Comment by RedSparr0w** [comment]
Auto entry enabled again.

Current setting is `3 seconds` per entry, looking at adding an option to adjust this though.
