### ISSUE TITLE
[BUG] Move "blacklist_apps" to local storage to increase size of list

### ISSUE THREAD

**Issue by Lakston** [RedSparr0w/IndieGala-Helper#16]
I added a couple of games multiple times on my blacklist but they keep showing up, examples : 

[Sleeping Valley](http://store.steampowered.com/app/538590/Sleeping_Valley/)

[Robowars](http://store.steampowered.com/app/285090/Robowars/?l=french)

I exported the list and edited it myself, adding the games to the json (in the right order) and re importing it, they show up in the blacklist but if I reload the page they are gone from the list and from the json file.

**Comment by RedSparr0w** [comment]
How many games do you have in your list, there is currently a limit, will have an update today/tomorrow that solves this.

To manually check how big your list is you can do the following in the console:

JSON.stringify(<<your json here>>).length + 16

If it's bigger than 8192 then it won't currently work

(On mobile at the moment will edit my comment for some better code later,
Will also double check that it is to do with the list size.)

Sent from my iPhone

On 15/07/2017, at 7:27 AM, Fabrice Pomata <notifications@github.com<mailto:notifications@github.com>> wrote:


I added a couple of games multiple times on my blacklist but they keep showing up, examples :

Sleeping Valley<http://store.steampowered.com/app/538590/Sleeping_Valley/>

Robowars<http://store.steampowered.com/app/285090/Robowars/?l=french>

I exported the list and edited it myself, adding the games to the json (in the right order) and re importing it, they show up in the blacklist but if I reload the page they are gone from the list and from the json file.

**Comment by Lakston** [comment]
Hey, thanks for the quick reply and indeed you are correct, I have a length of 8252, I also had forgotten to check my console and found out that when adding a game I get this error :

```
Unchecked runtime.lastError while running storage.set: QUOTA_BYTES_PER_ITEM quota exceeded
    at markAsOwned (chrome-extension://alhjnofcnnpeaphgeakdhkebafjcpeae/indiegala.js:83:22)
    at HTMLSpanElement.<anonymous> (chrome-extension://alhjnofcnnpeaphgeakdhkebafjcpeae/indiegala_giveaways.js:154:53)
    at HTMLDocument.dispatch (chrome-extension://alhjnofcnnpeaphgeakdhkebafjcpeae/jquery-3.1.0.min.js:3:9922)
    at HTMLDocument.q.handle (chrome-extension://alhjnofcnnpeaphgeakdhkebafjcpeae/jquery-3.1.0.min.js:3:7949)
```

Thanks for the script btw, if you need help with some features feel free to ask and I'll help if I can !

**Comment by Lakston** [comment]
What is the best practice regarding chrome storage limits ?

I've found that you can put

```
"permissions": [
  "unlimitedStorage"
]
```

in your `manifest.json`to avoid the 8192 bytes limit (see [here](https://stackoverflow.com/questions/22636771/chrome-storage-sync-vs-chrome-storage-local)) or create a new item when the limit is reached, items limit is 512 so that would cover all cases. (chrome specs [here](https://developer.chrome.com/extensions/storage#properties))

What is your take on that ?

**Comment by RedSparr0w** [comment]
Unfortunately unlimited storage only works for local storage and not the sync'd storage.

I will probably just move the blacklist games to local storage, which means it won't sync across computers but it will increase the amount you can add, and not too hard too backup and restore to other computers to keep the list the same.

The other option is to split the blacklist into multiple objects under the size limit and merge them again when you read the data back, but this will still be limited to a maximum amount.

So chances are it will be moved to local storage.

Sent from my iPhone

On 23/07/2017, at 2:53 AM, Fabrice Pomata <notifications@github.com<mailto:notifications@github.com>> wrote:


What is the best practice regarding chrome storage limits ?

I've found that you can put

"permissions": [
  "unlimitedStorage"
]```

in your `manifest.json`to avoid the 8192 bytes limit (see [here](https://stackoverflow.com/questions/22636771/chrome-storage-sync-vs-chrome-storage-local)) or vreate a new item when the limit is reached, items limit is 512 so that would cover all cases.

What is your take on that ?

**Comment by Lakston** [comment]
I can't talk for everyone but I don't mind it moving to local storage, especially since you added the possibility to export / import lists.

**Comment by Lakston** [comment]
Any news on this ? There are tons of games I'm hiding everyday but I have to do it again and again because they are not added to the json since its size is limited.

Thanks.

**Comment by RedSparr0w** [comment]
Sorry, Been super busy with work lately, Not sure when i am going to have time to look at this unfortunately.


But it is at the top of my priority list in regards to the extension.


________________________________

**Comment by Lakston** [comment]
no worries I can understand that !

I'll take a look at it if I have some time and submit a PR.

**Comment by Lakston** [comment]
I'll try to take a look at this this week.

**Comment by RedSparr0w** [comment]
Should be sorted now!
👍 
It may be able to be optimized more but will do for now.
