### ISSUE TITLE
[FIREFOX] Options Inconsistently Show/Work 

### ISSUE THREAD

**Issue by RedSparr0w** [RedSparr0w/IndieGala-Helper#20]
Reports of the options not saving/showing/working

Currently unable to reproduce to debug.

**Comment by Lucki** [comment]
I have this error in the web console, but I don't know if this has anything to do with it:
~~~
TypeError: window.getComputedStyle(...) is null [More Information]     framework7.min.js:21:12840
	css                      moz-extension://4a26c8da-[…]-f890f6eef8e3/include/js/framework7.min.js:21:12840
	window.Framework7        moz-extension://4a26c8da-[…]-f890f6eef8e3/include/js/framework7.min.js:15:3785
	<anonym>                 moz-extension://4a26c8da-[…]-f890f6eef8e3/options.js:30:13
~~~
- [More Information] leads to https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Unexpected_type
- Entry 1 points to: https://github.com/RedSparr0w/IndieGala-Helper/blob/85dd8046e0b0673523c60c20e23513c505b641bb/include/js/framework7.min.js#L21
- Entry 2 points to: https://github.com/RedSparr0w/IndieGala-Helper/blob/85dd8046e0b0673523c60c20e23513c505b641bb/include/js/framework7.min.js#L15
- Clicking on the last entry gets to Line 30 https://github.com/RedSparr0w/IndieGala-Helper/blob/85dd8046e0b0673523c60c20e23513c505b641bb/options.js#L29-L34

I hope this helps

**Comment by RedSparr0w** [comment]
Ill try updating framework 7 and see if that helps

Edit: Looks like its a problem with trying to use `window.getComputedStyle(...)` when the iframe is hidden.

Still not sure if changing that will fix it, but worth a try, will push a update soon.

**Comment by RedSparr0w** [comment]
Oops, Did not mean to close the issue.
But will leave it closed for now until someone can comeback and confirm if this is still a problem in `v 3.2.7`

**Comment by Lucki** [comment]
Menu shows up every time now. 👍

**Comment by RedSparr0w** [comment]
Glad to hear 😄 
Not a clue what i would have done to fix it otherwise.
