### ISSUE TITLE
[feature request] Register new keys in the browser

### ISSUE THREAD

**Issue by Lucki** [RedSparr0w/IndieGala-Helper#21]
Instead of opening Steam to register a key, open this URL in new tab with the key at the end: [https://store.steampowered.com/account/registerkey?key=AAAAA-BBBBB-CCCCC](https://store.steampowered.com/account/registerkey?key=AAAAA-BBBBB-CCCCC)

**Comment by RedSparr0w** [comment]
I've already implemented something similar to this [=
Just hasn't gone live yet,
With the newest version you can activate it straight from IndieGala without opening that page (will use whatever account is currently logged into the steam website).

I still need to do some testing first before i push it to the live version though.

![](https://i.imgur.com/TXqmyOM.png)
![](https://i.imgur.com/dWUUofk.png)

**Comment by Lucki** [comment]
Ha, thanks you take care of this.
However, using the link would give an extra confirmation step to verify the account the key gets bound to. But your implementation seems to be more convenient.

**Comment by RedSparr0w** [comment]
Latest release falls back on this method 👍
