### ISSUE TITLE
abandoned?

### ISSUE THREAD

**Issue by GregoryGHarding** [RedSparr0w/IndieGala-Helper#22]
is project abandoned? this has been broken for almost a month

**Comment by RedSparr0w** [comment]
Not abandoned, just haven't had much time to work on this lately.
Was also recently in contact with IndieGala in regards to working with them to implement these features directly to the website, but they are planning on doing this internally, so hopefully they will have that working without the extension soon.

I am pushing out an update today, i'm fairly sure most things are working but i can't test it all at the moment so if you do notice any things that are no longer working please open another issue 😄

**Comment by GregoryGHarding** [comment]
thanks for the update red
