### ISSUE TITLE
Entering giveaways broken on Firefox

### ISSUE THREAD

**Issue by pizzahut2** [RedSparr0w/IndieGala-Helper#24]
Since a few days it just says "error: unknown error" when entering a giveaway, independent of whether it's automatic or not. If I disable the extension, I can enter. It works fine when using Google Chrome.

Bit of discussion here: https://www.indiegala.com/forums/topics/594?page=last#last-post

**Comment by pizzahut2** [comment]
Hm this is weird, it started working again. Not closing it just yet, but this issue might have fixed itself somehow.

**Comment by pizzahut2** [comment]
It's broken again. I guess it's sorta random, lately I always get this "unknown error" when entering giveaways through Firefox, if the extension is enabled.

**Comment by pizzahut2** [comment]
Working again.

Edit: Now it's broken again.

**Comment by RedSparr0w** [comment]
Next time it breaks, could you open the developer console `F12` and let me know if you can see any error messages appear there.

**Comment by pizzahut2** [comment]
The only two errors in the console are probably unrelated.

Laden fehlgeschlagen für das <script> mit der Quelle "https://connect.facebook.net/en_US/fbevents.js".
Laden fehlgeschlagen für das <script> mit der Quelle "https://script.tapfiliate.com/tapfiliate.js".

https://i.imgur.com/vxfFS6F.png

Maybe the anti-virus interferes, though its browser extension is disabled, and no problems when using Chrome. It's a mystery why it randomly doesn't work.

https://pastebin.com/yJa4JY0T

**Comment by RedSparr0w** [comment]
Going to be dropping support for FireFox unfortunately.
Don't currently have much time to work on this overall.
