### ISSUE TITLE
Can't find setting in New Profile UI

### ISSUE THREAD

**Issue by Kureka** [RedSparr0w/IndieGala-Helper#26]
IG just released new profile UI, and I can't find IG Helper setting in that new one.

**Comment by xeblog** [comment]
Can confirm, I can't find it either.

**Comment by KeerealYo** [comment]
Yep. It shows points error and can't do autoenter

**Comment by xeblog** [comment]
It seems to be fixed! Thank you!

**Comment by Kureka** [comment]
Yes it's fixed now, at least in main page can setting.
