### ISSUE TITLE
IndieGala Helper not working in new giveaways page

### ISSUE THREAD

**Issue by Kureka** [RedSparr0w/IndieGala-Helper#27]
Looks like they completely change the page, so now it's not working at all

**Comment by xeblog** [comment]
Can confirm...

**Comment by RedSparr0w** [comment]
Should be fixed in the `v5` branch https://github.com/RedSparr0w/IndieGala-Helper/tree/v5
Uploaded to chrome webstore just a few minutes ago.

Some of the fixes are pretty crude, but it should be mostly working.

**Comment by GregoryGHarding** [comment]
still waiting for chrome to update the extension in the web store

**Comment by RedSparr0w** [comment]
> still waiting for chrome to update the extension in the web store

Yeah the process is taking longer than usual due to some changes they’ve made to the review process since I last updated, hopefully the update process should be quicker next time though.

**Comment by Kureka** [comment]
I just download the zip and load unpackage extension, can't wait for Chrome webstore lol.
