### ISSUE TITLE
(v5) Owned Game with Profile Features Limited, still listed on Giveaways Page

### ISSUE THREAD

**Issue by Kureka** [RedSparr0w/IndieGala-Helper#28]
Games like GraFi 4 and Data mining 7 still listed on giveaways page, even though I already owned those games.

**Comment by RedSparr0w** [comment]
Could you try manually updating your owned games list and see if it still appears.

![image](https://user-images.githubusercontent.com/7288322/84561251-f7ad7700-ad9e-11ea-8c4b-df350694af33.png)

**Comment by Kureka** [comment]
Yeah already try that, I guess profile features limited game not listed when pulled using Steam API. Even though it's listed in my library.

**Comment by RedSparr0w** [comment]
Should be fixed by https://github.com/RedSparr0w/IndieGala-Helper/commit/0db576600231adc75ae64f2403d817af64164e08
