### ISSUE TITLE
Error Extensions

### ISSUE THREAD

**Issue by Kureka** [RedSparr0w/IndieGala-Helper#33]
Uncaught SyntaxError: Identifier 'update_message' has already been declared
Context
https://www.indiegala.com/giveaways
Stack Trace
indiegala.js:34 (anonymous function)

Uncaught ReferenceError: get_user_level is not defined
Context
https://www.indiegala.com/giveaways
Stack Trace
indiegala_giveaways.js:28 (anonymous function)

**Comment by RedSparr0w** [comment]
Thanks for the report 😄
