### ISSUE TITLE
Reload Owned Games Loading Forever

### ISSUE THREAD

**Issue by Kureka** [RedSparr0w/IndieGala-Helper#34]
Reload Owned Games loading messages will stay forever until pressed OK manually.

**Comment by RedSparr0w** [comment]
Yeah, I had removed the loading message, was a problem for when the owned games list loaded too fast, it wouldn't dismiss the button 😅 
Fixed in https://github.com/RedSparr0w/IndieGala-Helper/commit/5215d137c985926a7636768e109b3ba070e42150
