### ISSUE TITLE
Infinite Scroll Not Working

### ISSUE THREAD

**Issue by Kureka** [RedSparr0w/IndieGala-Helper#35]
I think IG changes how their pagination works, so now it's broken.

Uncaught TypeError: Cannot read property 'top' of undefined
Context
https://www.indiegala.com/giveaways/2/expiry/asc/level/all
Stack Trace
indiegala_giveaways.js:181 (anonymous function)

**Comment by RedSparr0w** [comment]
Should be fixed with https://github.com/RedSparr0w/IndieGala-Helper/commit/b899007c0fef20cddf0736620218124b08b488a2
🤞
