### ISSUE TITLE
Use http://store.steampowered.com/dynamicstore/userdata/ instead

### ISSUE THREAD

**Issue by Revadike** [RedSparr0w/IndieGala-Helper#9]
GetOwnedApps by Steam's own Web API (and also Enhanced Steam's API) doesn't list all owned apps unfortunately (e.g. no owned DLC). I suggest you use http://store.steampowered.com/dynamicstore/userdata/ instead. That does list all owned apps (including DLC). Downside to this though is that it is cached by steam and the user needs to be logged in to the steam store to use. You can always fall back to GetOwnedGames web api and your cached data if dynamicstore is not available.

Nice extension btw.

**Comment by RedSparr0w** [comment]
Yeah i thought about doing that, but i feel its too hard to explain to people using the extension that they will have to be logged into the steam account associated with the indiegala login in order to function correctly.

**Comment by Revadike** [comment]
Why is it hard to explain?

**Comment by Revadike** [comment]
BTW, you can cache the data. Make them login to steam if they want to refresh it.

**Comment by RedSparr0w** [comment]
Do you happen to know if it will still show the owned games list if your profile is set to private?

Thinking i will update the script to either let user use their current logged in steam profile or user specified steam ID

**Comment by Revadike** [comment]
yes, it detects games from private profiles.

**Comment by RedSparr0w** [comment]
Should be fixed by https://github.com/RedSparr0w/IndieGala-Helper/commit/0db576600231adc75ae64f2403d817af64164e08
